### ISSUE TITLE
pubblic WIFI login redirects - false positives

### ISSUE THREAD

**Issue by alex9913** [max99x/pagemon-chrome-ext#345] opened 2015-03-27 12:33 UTC
when using a pubblic wifi (or in my case University access point) every page request is forwarded to a login page of the wifi provider. pagemon recognises those as "page updates" to all pages

I think the most practical solution would be to add a connection checker (ping google?) to make sure internet is available and returns a predicatble result (ex. google homepage titel and not wifi login)

Since I've moved to University dorms, this otherwise extremely useful plugin became useless.

Thank you so much for making this extension!

**Comment by alex9913** [comment] 2015-03-27 12:40
Sorry for reposting the same issue #231, butthose gateways are very popular (McDonnalds, Airports, Libraries...) and it really makes the extension completely non-effective.

**Comment by max99x** [comment] 2015-03-28 10:07
Duplicate of #231.

**Closed by max99x** 2015-03-28 10:07 UTC
